version: '3.8'

services:
  backend:
    build: ./backend
    container_name: omg-playlist-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - CORS_ORIGINS=http://localhost:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"] || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: omg-playlist-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  data:
    name: omg-playlist-data
